version: "3.0"
services:
  encryption-at-rest:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "encryption-at-rest"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INPUT_LABEL: "temperature"
    ports:
      - 80:80
